#!/bin/bash
# Copyright 2012 Kenneth Mitchner
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
# http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


if [ $# -ne 2 ] ; then
    echo "Usage: $0 OLD_NUMBER NEW_NUMBER"
    exit
fi

OLD_NUMBER=$1
NEW_NUMBER=$2
SERVER="r1-dev"

redis-cli -h $SERVER set INVENTORY_ACTION_${NEW_NUMBER} $( redis-cli -h $SERVER get INVENTORY_ACTION_${OLD_NUMBER} | sed -e "s/tracking_number\":\"[0-9]*/tracking_number\":\"$NEW_NUMBER/" );
echo "get INVENTORY_ACTION_${NEW_NUMBER}"
redis-cli -h $SERVER get INVENTORY_ACTION_${NEW_NUMBER}
