#!/bin/bash
# Script to allow human readable editing of redis data.
# By Ken Mitchner

if [ $# -gt 1 ] ; then
    echo "Usage: $0 REDIS_KEY"
    exit
fi

KEY=$1

TMPFILE=$(mktemp /tmp/XXXXXXXXXX.json)

redis-cli -h r1-dev get $1 >$TMPFILE
sed -i -e 's/{/{\n/g;s/}/\n}/g;s/,/,\n/g;' $TMPFILE
while(true) ; do
    vim -c 'argdo execute "normal gg=G" | update' $TMPFILE
    if [ -n "$( node --help 2>/dev/null | grep nodejs)" ] ; then
        REQNAME=$( echo -n $TMPFILE | sed -e 's/\.json$//g' )
        node -e "var validate = require('$REQNAME');" >/dev/null 2>&1
        if [ $? -ne 0 ] ; then
            echo "JSON Invalid! Hit Enter to Edit";
            read DOESNTMATTER
        else
            break
        fi
    else
        break
    fi
done
sed -i -e 's/^[ \t]*//g;' $TMPFILE
VALUE=$( cat $TMPFILE | tr -d "\n" )
echo
# Bash automatically escapes data in an environment variable.
# I output the sample to reflect how bash escapes it's data.
echo $VALUE | sed -e 's/"/\\"/g;s/$/"/g;s/^/"/g'
echo
echo -n "Send these changes to redis? (y/N): "
read N
if [[ "$N" =~ ^[yY]([eE][sS])?$ ]] ; then
    redis-cli -h r1-dev set $KEY $VALUE
fi 
rm $TMPFILE
